# Generated by Django 2.0.5 on 2018-05-21 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='Question Index')),
                ('question', models.TextField(verbose_name='Question')),
                ('value_type', models.TextField(choices=[('yesnobut', 'Yes or no but allow comment'), ('text', 'Single line text input'), ('textarea', 'Multi line text input')], verbose_name='Question Value Type')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='Question Group Index')),
                ('name', models.TextField(verbose_name='Question Group Name')),
                ('description', models.TextField(verbose_name='Question Group Description')),
            ],
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_groups', to='FAIRshakeRubric.Rubric'),
        ),
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='FAIRshakeRubric.QuestionGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='questiongroup',
            unique_together={('id', 'rubric')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('id', 'group', 'index')},
        ),
    ]
