# Generated by Django 2.0.7 on 2018-07-18 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Average',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.IntegerField(blank=True, null=True)),
                ('q_id', models.IntegerField(blank=True, null=True)),
                ('avg', models.FloatField(blank=True, null=True)),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('test', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'average',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('resource_id', models.IntegerField(blank=True, null=True)),
                ('q_id', models.IntegerField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('url_comment', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('test', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'evaluation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.TextField(blank=True, null=True)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('project_img', models.TextField(blank=True, null=True)),
                ('test', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.IntegerField(blank=True, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('f', models.TextField(blank=True, db_column='F', null=True)),
                ('a', models.TextField(blank=True, db_column='A', null=True)),
                ('i', models.TextField(blank=True, db_column='I', null=True)),
                ('r', models.TextField(blank=True, db_column='R', null=True)),
                ('res_type', models.TextField(blank=True, null=True)),
                ('test', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionInRubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'question_in_rubric',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionOld',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.IntegerField(blank=True, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('f', models.TextField(blank=True, db_column='F', null=True)),
                ('a', models.TextField(blank=True, db_column='A', null=True)),
                ('i', models.TextField(blank=True, db_column='I', null=True)),
                ('r', models.TextField(blank=True, db_column='R', null=True)),
                ('res_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'question_old',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_name', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('resource_type', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('test', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'resource',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('rubric_id', models.AutoField(primary_key=True, serialize=False)),
                ('rubric_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rubric',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RubricToResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'rubric_to_resource',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('role_evaluator', models.TextField(blank=True, null=True)),
                ('role_starter', models.TextField(blank=True, null=True)),
                ('test', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceInProject',
            fields=[
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='FAIRshakeAPI.Resource')),
            ],
            options={
                'db_table': 'resource_in_project',
                'managed': False,
            },
        ),
    ]
