# Generated by Django 2.0.7 on 2018-07-16 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.TextField(default='null')),
                ('comment', models.TextField(blank=True, default='', null=True)),
                ('url_comment', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('methodology', models.TextField(default='null')),
                ('requestor', models.TextField(default='null')),
                ('assessor', models.TextField(default='null')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orcid', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalObject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uri', models.TextField(null=True)),
                ('minid', models.TextField(null=True)),
                ('title', models.TextField(default='null')),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('image', models.TextField(blank=True, default='', null=True)),
                ('tags', models.TextField(blank=True, default='', null=True)),
                ('url', models.URLField(default='null')),
                ('type', models.TextField(default='null')),
                ('authors', models.ManyToManyField(to='FAIRshakeAPI.Author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uri', models.TextField(null=True)),
                ('minid', models.TextField(null=True)),
                ('title', models.TextField(default='null')),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('image', models.TextField(blank=True, default='', null=True)),
                ('tags', models.TextField(blank=True, default='', null=True)),
                ('type', models.TextField(default='null')),
                ('license', models.TextField(default='null')),
                ('rationale', models.URLField(default='null')),
                ('principle', models.URLField(default='null')),
                ('metrics', models.URLField(blank=True, default='', null=True)),
                ('fairsharing', models.URLField(blank=True, default='', null=True)),
                ('authors', models.ManyToManyField(to='FAIRshakeAPI.Author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uri', models.TextField(null=True)),
                ('minid', models.TextField(null=True)),
                ('title', models.TextField(default='null')),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('image', models.TextField(blank=True, default='', null=True)),
                ('tags', models.TextField(blank=True, default='', null=True)),
                ('url', models.URLField(blank=True, default='', null=True)),
                ('authors', models.ManyToManyField(to='FAIRshakeAPI.Author')),
                ('digital_objects', models.ManyToManyField(related_name='projects', to='FAIRshakeAPI.DigitalObject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uri', models.TextField(null=True)),
                ('minid', models.TextField(null=True)),
                ('title', models.TextField(default='null')),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('image', models.TextField(blank=True, default='', null=True)),
                ('tags', models.TextField(blank=True, default='', null=True)),
                ('type', models.TextField(default='null')),
                ('license', models.TextField(default='null')),
                ('authors', models.ManyToManyField(to='FAIRshakeAPI.Author')),
                ('metrics', models.ManyToManyField(related_name='rubrics', to='FAIRshakeAPI.Metric')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('role_evaluator', models.TextField(blank=True, null=True)),
                ('role_starter', models.TextField(blank=True, null=True)),
                ('test', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FAIRshakeAPI.User'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='FAIRshakeAPI.Project'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='rubric',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='FAIRshakeAPI.Rubric'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='target',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='FAIRshakeAPI.DigitalObject'),
        ),
        migrations.AddField(
            model_name='answer',
            name='assessment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='answers', to='FAIRshakeAPI.Assessment'),
        ),
        migrations.AddField(
            model_name='answer',
            name='metric',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='FAIRshakeAPI.Metric'),
        ),
    ]
