# Generated by Django 2.0.7 on 2018-07-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAIRshakeAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='requestor',
            field=models.TextField(null=True),
        ),
    ]
