# Generated by Django 2.0.7 on 2018-07-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAIRshakeAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='project',
        ),
        migrations.AddField(
            model_name='metric',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='rubric',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
