# Generated by Django 2.0.7 on 2018-07-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAIRshakeAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
    ]
