# Generated by Django 2.0.7 on 2018-07-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAIRshakeAPI', '0002_auto_20180725_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalobject',
            name='minid',
        ),
        migrations.RemoveField(
            model_name='digitalobject',
            name='uri',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='minid',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='uri',
        ),
        migrations.RemoveField(
            model_name='project',
            name='minid',
        ),
        migrations.RemoveField(
            model_name='project',
            name='uri',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='minid',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='uri',
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.TextField(blank=True, choices=[('', 'Other'), ('any', 'Any Digital Object'), ('data', 'Database'), ('repo', 'Repository'), ('test', 'Test Object'), ('tool', 'Tool')], default=''),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='answer',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='answer',
            name='url_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='methodology',
            field=models.TextField(choices=[('self', 'Digital Object Creator Assessment'), ('user', 'Independent User Assessment'), ('auto', 'Automatic Assessment'), ('test', 'Test Assessment')]),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='requestor',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='digitalobject',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='digitalobject',
            name='image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='digitalobject',
            name='tags',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='digitalobject',
            name='title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='digitalobject',
            name='type',
            field=models.TextField(blank=True, choices=[('', 'Other'), ('any', 'Any Digital Object'), ('data', 'Database'), ('repo', 'Repository'), ('test', 'Test Object'), ('tool', 'Tool')], default=''),
        ),
        migrations.AlterField(
            model_name='digitalobject',
            name='url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metric',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='metric',
            name='fairmetrics',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='metric',
            name='fairsharing',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='metric',
            name='image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='metric',
            name='license',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='metric',
            name='principle',
            field=models.TextField(blank=True, choices=[('F', 'Findability'), ('A', 'Accessibility'), ('I', 'Interoperability'), ('R', 'Reusability')], default=''),
        ),
        migrations.AlterField(
            model_name='metric',
            name='rationale',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='metric',
            name='tags',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='metric',
            name='type',
            field=models.TextField(blank=True, choices=[('', 'Other'), ('any', 'Any Digital Object'), ('data', 'Database'), ('repo', 'Repository'), ('test', 'Test Object'), ('tool', 'Tool')], default=''),
        ),
        migrations.AlterField(
            model_name='metric',
            name='url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='license',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='tags',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='type',
            field=models.TextField(blank=True, choices=[('', 'Other'), ('any', 'Any Digital Object'), ('data', 'Database'), ('repo', 'Repository'), ('test', 'Test Object'), ('tool', 'Tool')], default=''),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
