# Generated by Django 2.0.7 on 2018-07-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAIRshakeAPI', '0002_remove_author_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metric',
            old_name='metrics',
            new_name='fairmetrics',
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(blank=True, default=''),
        ),
    ]
