# Generated by Django 2.0.7 on 2018-08-17 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAIRshakeAPI', '0002_auto_20180817_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['id'], 'verbose_name': 'answer', 'verbose_name_plural': 'answers'},
        ),
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['id'], 'verbose_name': 'assessment', 'verbose_name_plural': 'assessments'},
        ),
        migrations.AlterModelOptions(
            name='assessmentrequest',
            options={'ordering': ['id'], 'verbose_name': 'assessment_request', 'verbose_name_plural': 'assessment_requests'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['id'], 'verbose_name': 'author', 'verbose_name_plural': 'authors'},
        ),
        migrations.AlterModelOptions(
            name='digitalobject',
            options={'ordering': ['id'], 'verbose_name': 'digital_object', 'verbose_name_plural': 'digital_objects'},
        ),
        migrations.AlterModelOptions(
            name='metric',
            options={'ordering': ['id'], 'verbose_name': 'metric', 'verbose_name_plural': 'metrics'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['id'], 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='rubric',
            options={'ordering': ['id'], 'verbose_name': 'rubric', 'verbose_name_plural': 'rubrics'},
        ),
    ]
