# Generated by Django 2.0.7 on 2018-07-30 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FAIRshakeAPI', '0003_auto_20180730_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='methodology',
            field=models.TextField(choices=[('self', 'Digital Object Creator Assessment'), ('user', 'Independent User Assessment'), ('auto', 'Automatic Assessment'), ('test', 'Test Assessment')], max_length=16),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='requestor',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='digitalobject',
            name='image',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='digitalobject',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='digitalobject',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='digitalobject',
            name='type',
            field=models.CharField(blank=True, choices=[('', 'Other'), ('any', 'Any Digital Object'), ('data', 'Database'), ('repo', 'Repository'), ('test', 'Test Object'), ('tool', 'Tool')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='digitalobject',
            name='url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='metric',
            name='image',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='metric',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='metric',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='metric',
            name='type',
            field=models.CharField(blank=True, choices=[('', 'Other'), ('any', 'Any Digital Object'), ('data', 'Database'), ('repo', 'Repository'), ('test', 'Test Object'), ('tool', 'Tool')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='metric',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(blank=True, choices=[('', 'Other'), ('any', 'Any Digital Object'), ('data', 'Database'), ('repo', 'Repository'), ('test', 'Test Object'), ('tool', 'Tool')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='image',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='type',
            field=models.CharField(blank=True, choices=[('', 'Other'), ('any', 'Any Digital Object'), ('data', 'Database'), ('repo', 'Repository'), ('test', 'Test Object'), ('tool', 'Tool')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
