# Generated by Django 2.0.7 on 2018-08-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAIRshakeAPI', '0003_auto_20180817_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='fairsharing',
        ),
        migrations.AddField(
            model_name='digitalobject',
            name='fairsharing',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
