# Generated by Django 2.0.7 on 2018-07-20 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FAIRshakeAPI', '0003_auto_20180719_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assessments', to='FAIRshakeAPI.Project'),
            preserve_default=False,
        ),
    ]
