# Generated by Django 2.0.7 on 2018-07-17 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FAIRshakeAPI', '0003_auto_20180717_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('FAIRshakeAPI.digitalobject',),
        ),
        migrations.AddField(
            model_name='digitalobject',
            name='rubrics',
            field=models.ManyToManyField(related_name='digital_objects', to='FAIRshakeAPI.Rubric'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answers', to='FAIRshakeAPI.Assessment'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='FAIRshakeAPI.Metric'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='url_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assessor',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='methodology',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='FAIRshakeAPI.Project'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='requestor',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='FAIRshakeAPI.Rubric'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='FAIRshakeAPI.DigitalObject'),
        ),
        migrations.AlterField(
            model_name='digitalobject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='digitalobject',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='digitalobject',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='digitalobject',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='digitalobject',
            name='type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='digitalobject',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='metric',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='fairmetrics',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='fairsharing',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='license',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='metric',
            name='principle',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='metric',
            name='rationale',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='metric',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='metric',
            name='type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='license',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='type',
            field=models.TextField(),
        ),
    ]
