# Generated by Django 2.0.7 on 2018-08-07 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FAIRshakeAPI', '0003_auto_20180807_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='FAIRshakeAPI.Project'),
        ),
    ]
