# Generated by Django 2.0.7 on 2018-07-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAIRshakeAPI', '0004_assessment_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalobject',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
