# Generated by Django 2.0.7 on 2018-07-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAIRshakeAPI', '0004_auto_20180730_1823'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.AlterField(
            model_name='metric',
            name='fairmetrics',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='metric',
            name='fairsharing',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='metric',
            name='license',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='metric',
            name='principle',
            field=models.CharField(blank=True, choices=[('F', 'Findability'), ('A', 'Accessibility'), ('I', 'Interoperability'), ('R', 'Reusability')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='license',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
