# Generated by Django 2.0.7 on 2018-08-08 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FAIRshakeAPI', '0005_auto_20180807_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'assessment_request',
                'verbose_name_plural': 'assessment_requests',
            },
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='requestor',
        ),
        migrations.AddField(
            model_name='assessmentrequest',
            name='assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='FAIRshakeAPI.Assessment'),
        ),
        migrations.AddField(
            model_name='assessmentrequest',
            name='requestor',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
