# Generated by Django 2.0.7 on 2018-09-12 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAIRshakeAPI', '0005_auto_20180917_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalobject',
            name='fairsharing',
        ),
    ]
