# Generated by Django 2.0.7 on 2018-07-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAIRshakeAPI', '0005_auto_20180730_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='type',
            field=models.CharField(blank=True, choices=[('yesnobut', 'Yes no or but question'), ('text', 'Simple textbox input'), ('url', 'A url input')], default='yesnobut', max_length=16),
        ),
    ]
