# Generated by Django 2.0.7 on 2018-09-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAIRshakeAPI', '0006_remove_digitalobject_fairsharing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalobject',
            name='url',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='metric',
            name='url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
