# Generated by Django 2.0.7 on 2018-08-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAIRshakeAPI', '0006_auto_20180808_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='methodology',
            field=models.TextField(blank=True, choices=[('self', 'Digital Object Creator Assessment'), ('user', 'Independent User Assessment'), ('auto', 'Automatic Assessment'), ('test', 'Test Assessment')], max_length=16),
        ),
    ]
