# Generated by Django 2.0.7 on 2018-12-10 21:52

from django.db import migrations

def forwards_func(apps, schema_editor):
    Answer = apps.get_model("FAIRshakeAPI", "Answer")
    db_alias = schema_editor.connection.alias
    for answer in Answer.objects.using(db_alias):
        answer.answer = {
            'yes'   : 1.00,
            'yesbut': 0.75,
            'maybe' : 0.50,
            'nobut' : 0.25,
            'no'    : 0.00,
            ''      : 0.00,
        }.get(answer.answer_tmp, 1)
        answer.save()

def reverse_func(apps, schema_editor):
    from scripts.linear_map import linear_map
    Answer = apps.get_model("FAIRshakeAPI", "Answer")
    db_alias = schema_editor.connection.alias
    for answer in Answer.objects.using(db_alias):
        answer.answer_tmp = linear_map(
            [0, 1],
            ['no', 'nobut', 'maybe', 'yesbut', 'yes'],
        )(answer.answer)
        answer.save()

class Migration(migrations.Migration):

    dependencies = [
        ('FAIRshakeAPI', '0008_auto_20181210_2142'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
