# Generated by Django 2.0.7 on 2018-12-10 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAIRshakeAPI', '0009_auto_20181210_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_tmp',
        ),
    ]
