# Generated by Django 2.0.7 on 2018-09-10 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAIRshakeAPI', '0009_auto_20180910_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answernew',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='answernew',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='assessmentnew',
            name='assessor',
        ),
        migrations.RemoveField(
            model_name='assessmentnew',
            name='project',
        ),
        migrations.RemoveField(
            model_name='assessmentnew',
            name='rubric',
        ),
        migrations.RemoveField(
            model_name='assessmentnew',
            name='target',
        ),
        migrations.RemoveField(
            model_name='assessmentrequestnew',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='assessmentrequestnew',
            name='requestor',
        ),
        migrations.RemoveField(
            model_name='digitalobjectnew',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='digitalobjectnew',
            name='rubrics',
        ),
        migrations.RemoveField(
            model_name='metricnew',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='projectnew',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='projectnew',
            name='digital_objects',
        ),
        migrations.RemoveField(
            model_name='rubricnew',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='rubricnew',
            name='metrics',
        ),
        migrations.DeleteModel(
            name='AnswerNew',
        ),
        migrations.DeleteModel(
            name='AssessmentNew',
        ),
        migrations.DeleteModel(
            name='AssessmentRequestNew',
        ),
        migrations.DeleteModel(
            name='DigitalObjectNew',
        ),
        migrations.DeleteModel(
            name='MetricNew',
        ),
        migrations.DeleteModel(
            name='ProjectNew',
        ),
        migrations.DeleteModel(
            name='RubricNew',
        ),
    ]
