# Generated by Django 2.0.7 on 2018-09-11 16:05

from django.db import migrations
import extensions.versions_ex.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('FAIRshakeAPI', '0010_auto_20180910_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=extensions.versions_ex.fields.CustomUUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='identity',
            field=extensions.versions_ex.fields.CustomUUIDField(),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='id',
            field=extensions.versions_ex.fields.CustomUUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='identity',
            field=extensions.versions_ex.fields.CustomUUIDField(),
        ),
        migrations.AlterField(
            model_name='assessmentrequest',
            name='id',
            field=extensions.versions_ex.fields.CustomUUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='digitalobject',
            name='id',
            field=extensions.versions_ex.fields.CustomUUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='digitalobject',
            name='identity',
            field=extensions.versions_ex.fields.CustomUUIDField(),
        ),
        migrations.AlterField(
            model_name='metric',
            name='id',
            field=extensions.versions_ex.fields.CustomUUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='metric',
            name='identity',
            field=extensions.versions_ex.fields.CustomUUIDField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=extensions.versions_ex.fields.CustomUUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='identity',
            field=extensions.versions_ex.fields.CustomUUIDField(),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='id',
            field=extensions.versions_ex.fields.CustomUUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='identity',
            field=extensions.versions_ex.fields.CustomUUIDField(),
        ),
    ]
