# Generated by Django 2.0.7 on 2018-12-11 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAIRshakeAPI', '0010_remove_answer_answer_tmp'),
        ('FAIRshakeAPI', '0010_auto_20180912_2054'),
    ]

    operations = [
    ]
