# Generated by Django 2.0.7 on 2018-09-12 20:50

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAIRshakeAPI', '0011_auto_20180911_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalobject',
            name='slug',
            field=models.CharField(max_length=255, default=None, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metric',
            name='slug',
            field=models.CharField(max_length=255, default=None, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.CharField(max_length=255, default=None, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubric',
            name='slug',
            field=models.CharField(max_length=255, default=None, null=True),
            preserve_default=False,
        ),
    ]
