# Generated by Django 2.0.12 on 2020-03-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAIRshakeAPI', '0011_auto_20190103_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
