# Generated by Django 2.0.12 on 2020-03-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAIRshakeAPI', '0012_assessment_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
