# Generated by Django 2.0.7 on 2018-09-12 20:51

from django.db import migrations

def migrate(apps, schema_editor):
    Project = apps.get_model('FAIRshakeAPI', 'Project')
    for project in Project.objects.all():
        project.slug = project.id
        project.save()

    DigitalObject = apps.get_model('FAIRshakeAPI', 'DigitalObject')
    for obj in DigitalObject.objects.all():
        obj.slug = obj.id
        obj.save()

    Rubric = apps.get_model('FAIRshakeAPI', 'Rubric')
    for rubric in Rubric.objects.all():
        rubric.slug = rubric.id
        rubric.save()

    Metric = apps.get_model('FAIRshakeAPI', 'Metric')
    for metric in Metric.objects.all():
        metric.slug = metric.id
        metric.save()

class Migration(migrations.Migration):

    dependencies = [
        ('FAIRshakeAPI', '0012_auto_20180912_2050'),
    ]

    operations = [
        migrations.RunPython(
            migrate
        )
    ]
