# Generated by Django 2.2.13 on 2020-09-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAIRshakeAPI', '0013_auto_20200312_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.CharField(max_length=28, primary_key=True, serialize=False)),
                ('scheme', models.CharField(max_length=16)),
                ('netloc', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('query', models.CharField(max_length=255)),
                ('fragment', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='metric',
            old_name='url',
            new_name='url_raw',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='url_raw',
        ),
        migrations.RenameField(
            model_name='rubric',
            old_name='url',
            new_name='url_raw',
        ),
        migrations.RenameField(
            model_name='digitalobject',
            old_name='url',
            new_name='url_raw',
        ),
    ]
