# Generated by Django 2.2.24 on 2024-10-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAIRshakeAPI', '0013_auto_20200312_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='type',
            field=models.CharField(choices=[('yesnobut', 'Yes no or but question'), ('yesnomaybe', 'Yes no or maybe question'), ('text', 'Simple textbox input'), ('url', 'A url input')], default='yesnobut', max_length=16),
        ),
    ]
