# Generated by Django 2.2.13 on 2020-09-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAIRshakeAPI', '0014_auto_20200929_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalobject',
            name='url',
            field=models.ManyToManyField(to='FAIRshakeAPI.Url'),
        ),
        migrations.AddField(
            model_name='metric',
            name='url',
            field=models.ManyToManyField(blank=True, to='FAIRshakeAPI.Url'),
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.ManyToManyField(blank=True, to='FAIRshakeAPI.Url'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='url',
            field=models.ManyToManyField(blank=True, to='FAIRshakeAPI.Url'),
        ),
    ]
