# Generated by Django 2.0.7 on 2018-09-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAIRshakeAPI', '0015_remove_digitalobject_fairsharing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='type',
            field=models.CharField(blank=True, choices=[('yesnobut', 'Yes no or but question'), ('yesnomaybe', 'Yes no or maybe question'), ('text', 'Simple textbox input'), ('url', 'A url input')], default='yesnobut', max_length=16),
        ),
    ]
