# Generated by Django 2.0.7 on 2018-09-17 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAIRshakeAPI', '0016_auto_20180917_1713'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('assessment', 'metric')},
        ),
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together={('project', 'target', 'rubric', 'methodology', 'assessor')},
        ),
    ]
