# Generated by Django 2.2.13 on 2020-09-29 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAIRshakeAPI', '0016_auto_20200929_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalobject',
            name='url_raw',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='url_raw',
        ),
        migrations.RemoveField(
            model_name='project',
            name='url_raw',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='url_raw',
        ),
    ]
