# Generated by Django 2.0.5 on 2018-05-21 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FAIRshakeHub', '0001_initial'),
        ('FAIRshakeRubric', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='FAIRshakeHub.Resource')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='FAIRshakeRubric.Rubric')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.FloatField(verbose_name='Running Average')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='FAIRshakeRubric.Question')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='FAIRshakeInsignia.Score')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='scoresummary',
            unique_together={('score', 'criterion')},
        ),
    ]
