# Generated by Django 2.0.5 on 2018-05-21 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FAIRshakeRubric', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('img', models.ImageField(upload_to='', verbose_name='Image')),
                ('rubrics', models.ManyToManyField(related_name='_project_rubrics_+', to='FAIRshakeRubric.Rubric')),
                ('users', models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('type', models.CharField(choices=[('T', 'Tool')], max_length=255, verbose_name='Type')),
                ('projects', models.ManyToManyField(related_name='resources', to='FAIRshakeHub.Project')),
                ('rubrics', models.ManyToManyField(related_name='_resource_rubrics_+', to='FAIRshakeRubric.Rubric')),
            ],
        ),
    ]
